OnlineCookbook/OnlineCookbook/accounts/urls.py
from django.urls import path

from OnlineCookbook.accounts import views


urlpatterns = [
    path('', views.ListProfilesView.as_view(), name='list profiles'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='log in'),
    path('logout/', views.UserLogoutView.as_view(), name='log out'),
    path('details/<int:pk>', views.ProfileDetailsView.as_view(), name='profile details'),
    path('edit/<int:pk>', views.ProfileEditView.as_view(), name='edit profile'),
]

OnlineCookbook/OnlineCookbook/urls.py
from django.conf.urls.static import static, settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OnlineCookbook.common.urls')),
    path('accounts/', include('OnlineCookbook.accounts.urls')),
    path('recipes/', include('OnlineCookbook.recipes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineCookbook/OnlineCookbook/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from OnlineCookbook.accounts.managers import OnlineCookbookUserManager


class OnlineCookbookUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        unique=True,
    )
    USERNAME_FIELD = 'email'

    is_staff = models.BooleanField(
        default=False,
    )
    is_superuser = models.BooleanField(
        default=False,
    )
    date_joined = models.DateTimeField(
        auto_now_add=True,
    )

    objects = OnlineCookbookUserManager()


class Profile(models.Model):
    profile_image = models.ImageField(
        upload_to='profiles',
        blank=True,
    )
    first_name = models.CharField(
        max_length=20,
        blank=True,
    )
    last_name = models.CharField(
        max_length=20,
        blank=True,
    )
    hometown = models.CharField(
        max_length=20,
        blank=True,
    )
    user = models.OneToOneField(
        OnlineCookbookUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )


from .signals import *

OnlineCookbook/OnlineCookbook/recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Recipe(models.Model):
    TYPE_CHOICE_MEAT_DISH = 'meat dish'
    TYPE_CHOICE_VEGETARIAN_DISH = 'vegetarian dish'
    TYPE_CHOICE_VEGAN_DISH = 'vegan dish'

    TYPE_CHOICES = (
        (TYPE_CHOICE_MEAT_DISH, 'Meat dish'),
        (TYPE_CHOICE_VEGETARIAN_DISH, 'Vegetarian dish'),
        (TYPE_CHOICE_VEGAN_DISH, 'Vegan dish'),
    )

    type = models.CharField(
        max_length=15,
        choices=TYPE_CHOICES,
    )
    title = models.CharField(
        max_length=50,
        blank=True,
    )
    ingredients = models.TextField(
        max_length=10000,
        blank=True,
    )
    instructions = models.TextField(
        max_length=10000,
        blank=True,
    )
    image = models.ImageField(
        upload_to='recipes',
        blank=True,
    )
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

OnlineCookbook/OnlineCookbook/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from OnlineCookbook.accounts.models import Profile

UserModel = get_user_model()


class RegisterForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('email',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)


"""Custom Login Form used with FBV"""
#
#
# class LoginForm(forms.Form):
#     user = None
#
#     email = forms.EmailField()
#
#     password = forms.CharField(
#         widget=forms.PasswordInput(),
#     )
#
#     def clean_password(self):
#         self.user = authenticate(
#             email=self.cleaned_data['email'],
#             password=self.cleaned_data['password'],
#         )
#         if not self.user:
#             raise ValidationError('Email and/or password incorrect')
#
#     def save(self):
#         return self.user

OnlineCookbook/OnlineCookbook/accounts/views.py
from django.contrib.auth import login

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView

from OnlineCookbook.accounts.forms import RegisterForm, ProfileForm
from OnlineCookbook.accounts.models import Profile
from OnlineCookbook.recipes.models import Recipe


class ListProfilesView(ListView):
    model = Profile
    template_name = 'accounts/list-profiles.html'
    context_object_name = 'profiles'


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        login(self.request, self.object)
        return result


class UserLoginView(LoginView):
    template_name = 'accounts/log-in.html'

    def get_success_url(self):
        return reverse_lazy('index')


class UserLogoutView(LogoutView):
    template_name = 'index.html'


class ProfileDetailsView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        profile = Profile.objects.get(user_id=self.kwargs.get('pk'))

        profile_owner = self.request.user.id == profile.user_id

        recipes_added_by_user = Recipe.objects.filter(user_id=profile.user_id)

        recipes_liked_by_user = Recipe.objects.filter(like__user=profile.user_id)

        context['profile'] = profile
        context['profile_owner'] = profile_owner
        context['recipes_added_by_user'] = recipes_added_by_user
        context['recipes_liked_by_user'] = recipes_liked_by_user
        return context


class ProfileEditView(UpdateView):
    model = Profile

    form_class = ProfileForm
    template_name = 'accounts/edit-profile.html'

    def get_success_url(self):
        return reverse_lazy('profile details', kwargs={'pk': self.kwargs['pk']})

OnlineCookbook/templates/accounts/edit-profile.html
{% extends 'shared/base.html' %}

{% block content %}
    <body class="text-center">

    <main class="form-signin">
        <h1 class="h3 mb-3 fw-normal"></h1>
        <h1 class="h3 mb-3 fw-normal">Edit your profile</h1>
        <form
                class="form-control me-2"
                method="post" action="{% url 'edit profile' profile.pk %}"
                enctype="multipart/form-data"
        >
            {% csrf_token %}
            <table align="center">
                {{ form.as_table }}
            </table>
            <button class="button btn-primary" type="submit">Update</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>


    </body>
{% endblock %}

OnlineCookbook/templates/accounts/list-profiles.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="album py-5 bg-light">
            <div class="container">

                {% if profiles %}
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                        {% for profile in profiles %}

                            <!-- Profile card -->
                            <div class="col">
                                <div class="card shadow-sm">


                                    <a href="{% url 'profile details' profile.pk %}">
                                        {% if profile.profile_image %}
                                            <img
                                                    src="{{ profile.profile_image.url }}"
                                                    width="200"
                                                    height="200"
                                            >
                                        {% else %}
                                            <img
                                                    src="{% static 'images/generic_user.jpg' %}"
                                                    width="200"
                                                    height="200"
                                            >
                                        {% endif %}
                                    </a>

                                    <div class="card-body">
                                        <p class="card-text">
                                        <h3>
                                            <small>User: </small>
                                            <strong>{{ profile.user }}</strong>
                                        </h3>
                                        <br>
                                        <h5>
                                            <small>Full name: </small>
                                            <i>{{ profile.first_name }} {{ profile.last_name }}</i>
                                        </h5>
                                        </p>
                                        <p class="card-text" size="1">From: {{ profile.hometown }}<br>
                                            Total recipes: {{ profile.user.recipe_set.count }}
                                        </p>
                                        <a href="{% url 'profile details' profile.pk %}">
                                            <button
                                                    type="button"
                                                    class="btn btn-sm btn-outline-secondary"
                                            >View user's profile and recipes
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h2>No profiles yet...</h2>
                {% endif %}
            </div>
        </div>

    </main>
{% endblock %}

OnlineCookbook/templates/accounts/log-in.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <body class="text-center">

    <main class="form-signin">
        <h1 class="h3 mb-3 fw-normal"></h1>
        <h1 class="h3 mb-3 fw-normal">Please log in</h1>
        <form class="form-control me-2" method="post" action="{% url 'log in' %}">
            {% csrf_token %}
            {{ form }}
            <button class="button btn-primary" type="submit">Log in</button>
            <p>
                <h5>If you don't have a profile create one <a href="{% url 'register' %}">here</a></h5>
            </p>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>


    </body>
{% endblock %}

OnlineCookbook/templates/accounts/profile-details.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <div class="row py-5 px-4">
        <div class="col-md-5 mx-auto">

            <!-- Recipe widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-4 pb-4 cover">
                    <div class="profile mr-3">
                        <div class="card-img-top">
                            {% if profile.profile_image %}
                                <img src="{{ profile.profile_image.url }}" alt="" width="200" height="200">
                            {% else %}
                                <img src="{% static 'images/generic_user.jpg' %}" alt="" width="200" height="200">
                            {% endif %}
                        </div>


                        <!-- User info -->
                        <div class="flex-md-column">
                            <h2 class="mt-0 mb-0">User: {{ profile.user.email }}</h2>
                            <h4 class="mt-0 mb-0">Full
                                name: {{ profile.first_name }} {{ profile.last_name }}</h4>
                            <p class="fas fa-map-marker-alt mr-1">From: {{ profile.hometown }}</p>
                        </div>


                        <!-- Check if current user is profile's user and add options -->
                        {% if profile_owner %}
                            <a href="{% url 'edit profile' profile.pk %}"
                               class="btn btn-outline-dark btn-sm btn-block">Edit profile</a>
                        {% endif %}


                        <!-- Recipes added by user -->
                        <div class="py-4 px-4">
                            <h5><u>User's recipes:</u></h5>

                            {% if recipes_added_by_user %}

                                {% for recipe in recipes_added_by_user %}
                                    <div class="col-lg-6 flex-column">

                                        <a href="{% url 'recipe details' recipe.id %}">
                                            {% if recipe.image %}
                                                <img
                                                        src="{{ recipe.image.url }}"
                                                        width="100"
                                                        height="100"
                                                        alt=""
                                                        class="img-fluid rounded shadow-sm">
                                            {% else %}
                                                <img
                                                        src="{% static 'images/generic_recipe.jpg' %}"
                                                        width="100"
                                                        height="100"
                                                        alt=""
                                                        class="img-fluid rounded shadow-sm">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <a><p>{{ recipe.title }}</p></a>
                                {% endfor %}
                                </div>

                            {% else %}
                                <h6>No recipes added by user</h6>
                            {% endif %}
                    </div>


                    <!-- Recipes liked by user -->
                    <div class="py-4 px-4">
                        <h5><u>Recipes liked by user:</u></h5>
                        {% if recipes_liked_by_user %}

                            {% for recipe in recipes_liked_by_user %}
                                <div class="col-lg-6 flex-column">

                                    <a href="{% url 'recipe details' recipe.id %}">
                                        {% if recipe.image %}
                                            <img
                                                    src="{{ recipe.image.url }}"
                                                    width="100"
                                                    height="100"
                                                    alt=""
                                                    class="img-fluid rounded shadow-sm">
                                        {% else %}
                                            <img
                                                    src="{% static 'images/generic_recipe.jpg' %}"
                                                    width="100"
                                                    height="100"
                                                    alt=""
                                                    class="img-fluid rounded shadow-sm">
                                        {% endif %}
                                    </a>
                                </div>
                                <a><p>{{ recipe.title }}</p></a>
                            {% endfor %}
                            </div>

                        {% else %}
                            <h6>No recipes liked by user</h6>
                        {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

OnlineCookbook/templates/accounts/register.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <body class="text-center">

    <main class="form-signin">
        <h1 class="h3 mb-3 fw-normal"></h1>
        <h1 class="h3 mb-3 fw-normal">Create a profile</h1>
        <form class="form-control me-2" method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {{ form }}
            <br>
            <button class="button btn-primary" type="submit">Register</button>
            <p>
                <h5>Already registered? Log-in <a href="{% url 'log in' %}">here</a></h5>
            </p>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>


    </body>
{% endblock %}

OnlineCookbook/templates/accounts/view-profile.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <div class="row py-5 px-4">
        <div class="col-md-5 mx-auto">

            <!-- Recipe widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-4 pb-4 cover">
                    <div class="profile mr-3">
                        <div class="card-img-top">
                            {% if profile.profile_image %}
                                <img src="{{ profile.profile_image.url }}" alt="" width="200" height="200">
                            {% else %}
                                <img src="{% static 'images/generic_user.jpg' %}" alt="" width="200" height="200">
                            {% endif %}
                        </div>


                        <!-- User info -->
                        <div class="flex-md-column">
                            <h2 class="mt-0 mb-0">User: {{ profile.user.email }}</h2>
                            <h4 class="mt-0 mb-0">Full
                                name: {{ profile.first_name }} {{ profile.last_name }}</h4>
                            <p class="fas fa-map-marker-alt mr-1">From: {{ profile.hometown }}</p>
                        </div>


                        <!-- Check if current user is profile's user and add options -->
                        {% if profile_owner %}
                            <a href="{% url 'edit profile' profile.pk %}"
                               class="btn btn-outline-dark btn-sm btn-block">Edit profile</a>
                        {% endif %}


                        <!-- Recipes added by user -->
                        <div class="py-4 px-4">
                            <h5><u>User's recipes:</u></h5>

                            {% if recipes_added_by_user %}

                                {% for recipe in recipes_added_by_user %}
                                    <div class="col-lg-6 flex-column">

                                        <a href="{% url 'view recipe' recipe.id %}">
                                            {% if recipe.image %}
                                                <img
                                                        src="{{ recipe.image.url }}"
                                                        width="100"
                                                        height="100"
                                                        alt=""
                                                        class="img-fluid rounded shadow-sm">
                                            {% else %}
                                                <img
                                                        src="{% static 'images/generic_recipe.jpg' %}"
                                                        width="100"
                                                        height="100"
                                                        alt=""
                                                        class="img-fluid rounded shadow-sm">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <a><p>{{ recipe.title }}</p></a>
                                {% endfor %}
                                </div>

                            {% else %}
                                <h6>No recipes added by user</h6>
                            {% endif %}
                    </div>


                    <!-- Recipes liked by user -->
                    <div class="py-4 px-4">
                        <h5><u>Recipes liked by user:</u></h5>
                        {% if recipes_liked_by_user %}

                            {% for recipe in recipes_liked_by_user %}
                                <div class="col-lg-6 flex-column">

                                    <a href="{% url 'view recipe' recipe.id %}">
                                        {% if recipe.image %}
                                            <img
                                                    src="{{ recipe.image.url }}"
                                                    width="100"
                                                    height="100"
                                                    alt=""
                                                    class="img-fluid rounded shadow-sm">
                                        {% else %}
                                            <img
                                                    src="{% static 'images/generic_recipe.jpg' %}"
                                                    width="100"
                                                    height="100"
                                                    alt=""
                                                    class="img-fluid rounded shadow-sm">
                                        {% endif %}
                                    </a>
                                </div>
                                <a><p>{{ recipe.title }}</p></a>
                            {% endfor %}
                            </div>

                        {% else %}
                            <h6>No recipes liked by user</h6>
                        {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}